### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by davechurchill** [ameDev21/Assignment3#1]
Hello,

In an attempt to keep publicly searchable solution code for my courses off of GitHub, would you mind either:

- Making this repo private, or
- Removing references to either the course name, or my name from the repo

This would go a long way to keeping solution code away from students of the course.

Thanks!

**Comment by ameDev21** [comment]
I apologize, I will make the repo private. I’m a great admirer of your work professor. I thank you for teaching this course in public. Sure has been one of my favorite course I took on the topic. On 6 Dec 2023, at 06:04, David Churchill ***@***.***> wrote:﻿
Hello,
In an attempt to keep publicly searchable solution code for my courses off of GitHub, would you mind either:

Making this repo private, or
Removing references to either the course name, or my name from the repo

This would go a long way to keeping solution code away from students of the course.
Thanks!

**Comment by davechurchill** [comment]
No worries, thank you!

**Comment by d9j** [comment]
wayback machine still can be used as backup solution :D
